name: Run Spotify report every hour or Manually

on:
  schedule:
    # 06h à 23h heure locale → 04h à 21h UTC
    - cron: '0 6-23 * * *'
    # 00h à 02h heure locale → 22h à 0h UTC (jour précédent et jour suivant)
    - cron: '0 0-2 * * *'
  workflow_dispatch:  # Lancement manuel uniquement

jobs:
  run-spotify-report:
    runs-on: self-hosted
    timeout-minutes: 5
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13.5'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run main.py
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          REDIRECT_URI: ${{ secrets.REDIRECT_URI }}
          SENDER_MAIL: ${{ secrets.SENDER_MAIL }}
          SENDER_APP_PASSWORD: ${{ secrets.SENDER_APP_PASSWORD }}
          RECEIVER_MAIL: ${{ secrets.RECEIVER_MAIL }}
          DATA_DIR: ${{ secrets.DATA_DIR_DELL }}
          TOKEN_CACHE_PATH: ${{ secrets.TOKEN_PATH_DELL }}
        run: |
          python scripts/main.py
