name: Run Spotify report every hour

on:
  schedule:
    - cron: '0 * * * *'   # Toutes les heures
  workflow_dispatch:       # Permet aussi un lancement manuel

jobs:
  run-spotify-report:
    runs-on: self-hosted
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download previous data
        uses: actions/download-artifact@v4
        with:
          name: spotify-data
          path: data
        continue-on-error: true  # La 1ère fois, il n’y a rien

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13.5'  # Ou la version que tu utilises

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run main.py
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          REDIRECT_URI: ${{ secrets.REDIRECT_URI }}
          SENDER_MAIL: ${{ secrets.SENDER_MAIL }}
          SENDER_APP_PASSWORD: ${{ secrets.SENDER_APP_PASSWORD }}
          RECEIVER_MAIL: ${{ secrets.RECEIVER_MAIL }}
        run: |
          python scripts/main.py


      - name: Upload updated data
        uses: actions/upload-artifact@v4
        with:
          name: spotify-data
          path: data